name: deploy

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy_shinyapps:
    name: Deploy to shinyapps.io

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set-up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set-up R environment
        uses: r-lib/actions/setup-renv@v2

      - name: Install dependencies
        run: Rscript install-deps.R

      - name: Localize dataset
        run: Rscript localize-dataset.R

      - name: Deploy app
        run: |
          rsconnect::setAccountInfo("${{ secrets.SHINYAPPS_ACCOUNT_NAME }}", "${{ secrets.SHINYAPPS_ACCOUNT_TOKEN }}", "${{ secrets.SHINYAPPS_ACCOUNT_SECRET }}")
          rsconnect::deployApp(appName = "${{ secrets.SHINYAPPS_APPLICATION_NAME }}", server = "${{ secrets.SHINYAPPS_APPLICATION_SERVER }}")
        shell: Rscript {0}
